INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('SHOPPING IBIRAPUERA', 'SP', 'São Paulo', 'Indianópolis', 'Avenida Ibirapuera, 3103 - lojas 4 e 5', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPNG IGUATEMI ALPHAVILLE', 'SP', 'Barueri', 'Alphavile Industrial', 'Alameda Rio Negro, 111 – lojas 337, 338, 339, 340 e 341', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING IGUATEMI SP', 'SP', 'São Paulo', 'Jardim Paulistano', 'Avenida Brigadeiro Faria Lima, 2.232 Loja ES 01', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('POLO SHOPPING INDAIATUBA', 'SP', 'Idaiatuba', 'Pimenta', 'Alameda Filtros Mann, s/nº, loja A04', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('C-SHOPPING INTERLAGOS', 'SP', 'São Paulo', 'Campo Grande', 'Avenida Interlagos, 2255 - Loja "Arco A"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ITAPE SHOPPING', 'SP', 'Itapetininga', 'Centro', 'RUA DOUTOR COUTINHO 733', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PLAZA SHOPPING ITU', 'SP', 'Itu', 'Jardim Paraíso', 'Avenida Doutor Ermelindo Maffei, 1199, loja 113', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('JACAREÍ SHOPPING', 'SP', 'Jacareí', 'Centro', 'Rua Olímpio Catão, 500 – loja 150', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MAXI SHOPPING', 'SP', 'Jundiaí', 'Jardim Rio Branco', 'Avenida Antônio Fred Ozanan, 6000 - loja 38', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('JUNDIAÍ SHOPPING', 'SP', 'Jundiaí', 'Alto do Anhangabaú', 'Avenida 9 de Julho, nº 3333 - loja 145', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING JARDIM SUL', 'SP', 'São Paulo', 'Vila Andrade', 'Avenida Giovanni Gronchi, 5819 - LUC 001', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PÁTIO LIMEIRA', 'SP', 'Limeira', 'Centro', 'Rua Carlos Gomes, 1.321, loja 212, âncora 2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MARILIA SHOPPING CENTER', 'SP', 'Marília', 'Jardim Maria Martha', 'Rua dos Tucunarés, 500, loja âncora L-140', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MAUA PLAZA SHOPPING', 'SP', 'Mauá', 'Jardim Rosina', 'Avenida Governador Mário Covas Júnior, 01 - loja 151', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BURITI SHOPPING MOGI GUAÇU', 'SP', 'Mogi Guaçu', 'Centro', 'Rua Francisco Franco de Godoy Bueno, 801 – loja 100/101', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING MOGI', 'SP', 'Mogi das Cruzes', 'Jardim Armênia', 'Avenida Vereador Narciso Yague Guimarães, 1.001, loja A 27', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING MORUMBI', 'SP', 'São Paulo', 'Vila São Francisco', 'Avenida Roque Petroni Júnior, 1089 - loja 1', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('OSASCO CENTRO', 'SP', 'Osasco', 'Centro', 'Rua Antônio Agú, 487', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING UNIÃO', 'SP', 'Osasco', 'Vila Yara', 'Avenida dos Autonomistas, 1.400, loja âncora "M"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SUPER SHOPPING OSASCO', 'SP', 'Osasco', 'Osasco', 'Avenida dos Autonomistas, 1828 - Piso 2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PENHA', 'SP', 'São Paulo', 'Penha de França', 'Rua Doutor João Ribeiro, 304 Lojas Âncoras C e F', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LITORAL SHOPPING', 'SP', 'Praia Grande', 'Intermarés', 'Avenida Ayrton Senna da Silva, 1.511 - Loja âncora A6', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PRUDENSHOPPING', 'SP', 'Presidente Prudente', 'Vila Santa Helena', 'Avenida Manoel Goulart, 2400, loja âncora 246/247', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PARQUE SHOPPING BARUERI', 'SP', 'Barueri', 'Aldeia', 'Rua General de Divisão de Pedro Rodrigues da Silva, 400 – loja 2037, piso L02', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PLAZA SHOPPING CARAPICUÍBA', 'SP', 'Carapicuíba', 'Vila Silvania', 'Estrada Ernestina Vieira 149', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('RIBEIRAO SHOPPING', 'SP', 'Ribeirão Preto', 'Jardim Califórnia', 'Avenida Coronel Fernando Ferreira Leite, 1540 - loja 38', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('RIO CLARO SHOPPING', 'SP', 'Rio Claro', 'Vila Paulista', 'Avenida Conde Francisco Matarazzo Júnior, 205 - Âncora B', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('NOVO SHOPPING', 'SP', 'Ribeirão Preto', 'Ribeirânia', 'Avenida Presidente Kennedy, 1.500, loja âncora "S"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('RAPOSO SHOPPING', 'SP', 'São Paulo', 'Jardim Olympia', 'Rodovia Raposo Tavares, s/nº, Km 14,5 - lojas 3001 e 3002', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SANTANA PARQUE SHOPPING', 'SP', 'São Paulo', 'Mandaqui', 'Rua Conselheiro Moreira de Barros, 2780, loja 2011 - 2º pavimento', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SAO BERNARDO DO CAMPO', 'SP', 'São Bernardo do Campo', 'Centro', 'Rua: Marechal Deodoro, 1078', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('GOLDEN SQUARE SHOPPING', 'SP', 'Vila Marlene', 'Vila Marlene', 'Avenida Kennedy, 700 - São Bernardo do Campo - Loja ancora piso L1 E L2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METRÓPOLE', 'SP', 'São Bernardo do Campo', 'Centro', 'Praça Samuel Sabatini, 200, loja LSU-4', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SÃO BENTO', 'SP', 'São Paulo', 'Centro histórico de São Paulo', 'R. São Bento, 230', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING BOURBON POMPÉIA', 'SP', 'São Paulo', 'Perdizes', 'Rua Turiassu, 2.100, loja 117, 2º piso', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SÃO BERNARDO PLAZA', 'SP', 'São Bernardo', 'Ferrazópolis', 'Avenida Albert Schweitzer, 256 – loja 1046', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPP. IGUATEMI SAO CARLOS', 'SP', 'São Carlos', 'Parque Faber', 'Passeio dos Flamboyants, 200, loja 91, piso térreo', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CENTER NORTE', 'SP', 'São Paulo', 'Vila Guilherme', 'Travessa Casalbuono, 120 - loja 610', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PARK SHOPPING SÃO CAETANO', 'SP', 'São Paulo', 'Cerâmica', 'Alameda Terracota, 545, loja 1007/2007', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CANTAREIRA NORTE SHOPPING', 'SP', 'Jardim Pirituba', 'Jardim Pirituba', 'Endereço: Avenida Raimundo Pereira de Magalhães, 11.001 – loja 1002/2002', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ITAPECERICA', 'SP', 'Itapecerica da Serra', 'Centro', 'Avenida Quinze de Novembro, 89 – loja âncora L2015', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METRO ITAQUERA', 'SP', 'Itaquera', 'Itaquera', 'Avenida José Pinheiro Borges, s/nº - lojas 101/201, Gleba I', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTER VALE SHOPPING', 'SP', 'São José dos Campos', 'Jardim Oswaldo Cruz', 'Avenida Deputado Benedito Matarazzo, 9403 - Loja "H"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING JARDIM ORIENTE', 'SP', 'São José dos Campos', 'Jardim América', 'Rua Andorra, 500 – Loja âncora piso térreo', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING MAIS', 'SP', 'São Paulo', 'Jardim Imbé', 'R. Etelvino Pedro dos Santos, 25', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MOOCA PLAZA SHOPPING', 'SP', 'São Paulo', 'Vila Prudente', 'Rua Capitão Pacheco e Chaves, 313 – loja 2049', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PÁTIO CIANÊ', 'SP', 'Sorocaba', 'Centro', 'Avenida Afonso Vergueiro, 823 – loja 104, Espaços Comerciais nº 06 e 07', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESPLANADA SHOPP. SOROCABA', 'SP', 'Votorantim', 'Parque Morumbi', 'Avenida Gisele Constantino, 1870, Box 230, 231, 232 e 233', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING D', 'SP', 'São Paulo', 'Canindé', 'Avenida Cruzeiro do Sul, 1.100, SUC 2000, 2º piso', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ELDORADO', 'SP', 'São Paulo', 'Pinheiros', 'Avenida Rebouças, 3970, lojas 231 a 234, 236A, 239, 246 e 279, 1º Piso', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PIRACICABA', 'SP', 'Piracicaba', 'Vila Rezende', 'Avenida Limeira, 722 - loja âncora C', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SP MARKET', 'SP', 'São Paulo', 'Vila Almeida', 'Avenida das Nações Unidas, 22.540, loja A7 - 17/18/19, Bloco C', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPING PLAZA SUL', 'SP', 'São Paulo', 'Jardim da Saúde', 'Pça. Leonor Kaupa, 100 - lojas 119 e 225', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CIDADE NORTE', 'SP', 'São José do Rio Preto', 'Jardim Marajó', 'Avenida Alfredo Antônio de Oliveira, 2077', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING RIO PRETO', 'SP', 'São José do Rio Preto', 'Jardim Morumbi', 'Avenida Brigadeiro Faria Lima, 6.363, SUC 286, Bloco E', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SANTO ANDRE CENTRO', 'SP', 'Santo André', 'Centro', 'Rua Campos Salles, 235/247', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TRIMAIS HIPER
CENTER', 'SP', 'São Paulo', 'Tucuruvi', 'Avenida TUCURUVI Nº: 248', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CONJTO ATLANTICO', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 575/576 e Sobreloja', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SUZANO', 'SP', 'Suzano', 'Guaio', 'Rua Sete de Setembro, 555, lojas 09/10/11/12/13A/13B', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TABOAO DA SERRA', 'SP', 'Taboão da Serra', 'Vila das Oliveiras', 'Rodovia Regis Bittencourt, Km 271,5 s/n.', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METRO TATUAPE', 'SP', 'São Paulo', 'Tatuapé', 'Rua Domingos Agostin, 91 - Loja Âncora 2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TAMBORE', 'SP', 'Barueri', 'Tamboré', 'Avenida Piracema, 669 - Lojas Âncoras D1 e D2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TAUBATÉ', 'SP', 'Taubaté', 'Vila Costa', 'Avenida Charles Schnneider, 1700, LUC A1, Piso Térreo', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TIVOLI', 'SP', 'Santa Bárbara D''Oeste', 'Vila Mollon', 'Avenida Santa Bárbara, 777 - loja âncora 1', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TIETÊ PLAZA', 'SP', 'São Paulo', 'Jardim Íris', 'Avenida Raimundo Pereira de Magalhães, 1465 – loja âncora 1000', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING VALE SUL', 'SP', 'São José dos Campos', 'Jardim Satélite', 'Avenida Andrômeda, 227, SUC 150', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING WEST PLAZA', 'SP', 'São Paulo', 'Água Branca', 'Pça. Tomas Morus, 408 - Bloco B - Térreo - lj.201', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Enxuto Supemercados', 'SP', 'Campinas', 'Jardim Aurélia', 'Avenida John Boyd Dunlop, 440', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Errejota bar', 'SP', 'Santo André', 'Jardim', 'Alameda São Caetano, 366', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Muquiranas', 'SP', 'Santo André', 'Campestre', 'Rua das Figueiras, 130', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Bar Aurora', 'SP', 'São Paulo', 'Vila Nova Conceição', 'Rua Professor Atílio Innocenti, 277', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Santa Julia', 'SP', 'São Paulo', 'Vila Olímpia', 'Alameda Raja Gabaglia, 129', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Kia Ora', 'SP', 'São Paulo', 'Vila Nova Conceição', 'Rua Doutor Eduardo de Souza Aranha, 377', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Pra Ti Faria', 'SP', 'São Paulo', 'Jardim Paulistano', 'Avenida Brigadeiro Faria Lima, 2627', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Pasquim Bar E Prosa', 'SP', 'São Paulo', 'Casa Verde', 'Rua Domingos Fasolari, 22', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Vero Piazza Bar', 'SP', 'São Paulo', 'Pinheiros', 'Praça dos Omaguás, 62', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Pasquim Bar E Prosa', 'SP', 'São Paulo', 'Pinheiros', 'Rua Fradique Coutinho, 1097', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('A Mata', 'SP', 'São Paulo', 'Pinheiros', 'Rua Cunha Gago, 832', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Iscondido Bar', 'SP', 'São Paulo', 'Cerqueira César', 'Rua Lisboa, 449', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Pasquim Bar E Prosa', 'SP', 'São Paulo', 'Parque da Mooca', 'Rua Ibipetuba, 204', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Templo Bar', 'SP', 'São Paulo', 'Mooca', 'Rua Guaimbé, 322', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Martin Bar', 'SP', 'São Paulo', 'Tatuapé', 'Rua Apucarana, 1490', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Cave Pool', 'SP', 'São Paulo', 'Instituto de Previdência', 'Avenida Eliseu de Almeida, 984', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Tata Japa', 'SP', 'São Paulo', 'Vila Nova Conceição', 'Rua João Cachoeira, 278', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Blue''s Bear', 'SP', 'São Paulo', 'Santana', 'Rua Heliodora, 390', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Banri', 'SP', 'São Paulo', 'Liberdade', 'Rua Galvão Bueno, 160', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Casa de Francisca', 'SP', 'São Paulo', 'Sé', 'Rua Quintino Bocaiúva, 22', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Casa Do porco', 'SP', 'São Paulo', 'República', 'Rua Araújo, 124', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Deus X Machine', 'SP', 'São Paulo', 'Pinheiros', 'Avenida Rebouças, 3658', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Rock Wheels', 'SP', 'São Paulo', 'Aclimação', 'Rua Bráz Cubas, 168', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Gula Bar', 'SP', 'São Paulo', 'Cidade Nova Heliópolis', 'Avenida Almirante Delamare, 592', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Stunt Burguer', 'SP', 'São Paulo', 'Vila Progredior', 'Rua José Jannarelli, 426', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('The Blue Pub', 'SP', 'São Paulo', 'Bela Vista', 'Alameda Ribeirão Preto, 384', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Whyplash', 'SP', 'São Paulo', 'Cerqueira César', 'Rua Melo Alves, 74', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Sororoca Bar', 'SP', 'São Paulo', 'Pinheiros', 'Rua Simão Álvares, 785', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Pappa Gallo', 'SP', 'São Paulo', 'Jardim Paulista', 'Alameda Jaú, 1372', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Lúdico', 'SP', 'São Paulo', 'Vila Mariana', 'Rua Joaquim Távora, 1113', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('O Burguer', 'SP', 'São Paulo', 'Planalto Paulista', 'Avenida Moaci, 806', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Stell Bar', 'SP', 'São Paulo', 'Indianópolis', 'Alameda dos Jurupis, 1806', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true),
('Castro Bar', 'SP', 'São Paulo', 'Vila Mariana', 'Rua Joaquim Távora, 1517', ARRAY['Vidro']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Empresa privada', true);