INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('Presid Prudente 14', 'SP', 'Presidente Prudente', 'Prq Res Damha', 'AVENIDA MIGUEL DAMHA, 145', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP São Miguel Pta 4', 'SP', 'São Paulo', 'C N S Miguel', 'AVENIDA NORDESTINA, 2612', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Artur Alvim 3', 'SP', 'São Paulo', 'Jardim Nordeste', 'PRACA ARAMA, 58', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Poá 2', 'SP', 'Poá', 'Centro', 'AVENIDA VINTE E SEIS DE MARÇO, 445', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Limão 3', 'SP', 'São Paulo', 'Jardim Cachoeira', 'RUA EDMUNDO KRUG, 50', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Vila Buarque 2', 'SP', 'São Paulo', 'Vila Buarque', 'RUA DAS PALMEIRAS, 303', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Santa Cruz R Pardo', 'SP', 'Santa Cruz do Rio Pardo', 'Vila Santa Aureliana', 'AV CORONEL CLEMENTINO GONCALVES, 281', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Bariri 2', 'SP', 'Bariri', 'Centro', 'RUA SETE DE SETEMBRO, 1126', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Embu das Artes 3', 'SP', 'Embu das Artes', 'Jd Jurema', 'RUA AUGUSTO DE ALMEIDA BATISTA, 336', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Sorocaba 20', 'SP', 'Sorocaba', 'Eden', 'AVENIDA INDEPENDENCIA, 4714', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Carapicuíba 4', 'SP', 'Carapicuíba', 'Vila Merces', 'AV INOCENCIO SERAFICO, 1750', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Paraguaçu Pta', 'SP', 'Paraguaçu Paulista', 'Centro', 'AVENIDA PARAGUASSU, 460', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Limão 4', 'SP', 'São Paulo', 'Limão', 'AVENIDA NOSSA SENHORA DO O, S/N', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Vila Romana 4', 'SP', 'São Paulo', 'Vila Romana', 'RUA MARCO AURELIO, 844', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Barueri 3', 'SP', 'Barueri', 'Bethaville I', 'AVENIDA TRINDADE, 157', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('S Bernardo Campo 24', 'SP', 'São Bernardo do Campo', 'Jd Chacara Inglesa', 'AVENIDA BARAO DE MAUA, 180', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('S Caetano do Sul 15', 'SP', 'São Caetano do Sul', 'Santa Paula', 'RUA OSWALDO CRUZ, 1148', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Osasco 21', 'SP', 'Osasco', 'Jaguaribe', 'AVENIDA JOSE LOURENCO, 611', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Taboão da Serra 8', 'SP', 'Taboão da Serra', 'Jardim Clementino', 'ESTRADA KIZAEMON TAKEUTI, 1349', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('SP Vl St Catarina 1', 'SP', 'São Paulo', 'Vila Campestre', 'RUA GUIAN, 13', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Mauá 5', 'SP', 'Mauá', 'Vila Augusto', 'AVENIDA ITAPARK, 754', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Valinhos 5', 'SP', 'Valinhos', 'Jardim Paiquere', 'RUA PAIQUERE, 1714', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Alphaville 5', 'SP', 'Barueri', 'Alphaville Empresarial', 'ALAMEDA RIO NEGRO, 1084', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Alphaville 4', 'SP', 'Barueri', 'A Industrial', 'ALAMEDA ARAGUAIA, 500', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Cooperviva', 'SP', 'Campinas', 'Jardim São Gabriel', 'Rua Luís Smânio, 80', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-17:00h', 'Fechado', 'Empresa privada', true),
('Cooperativa de Reciclagem Jardim Eulina', 'SP', 'Campinas', 'Jardim Eulina', 'Rua Sebastião Jardim, 180', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-17:00h', 'Fechado', 'Empresa privada', true),
('Cooperativa de Reciclagem da Vila União', 'SP', 'Campinas', 'Vila União', 'Rua Enzo Ferrari, 120', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-17:00h', 'Fechado', 'Empresa privada', true),
('PEV Barão Geraldo', 'SP', 'Campinas', 'Jardim América', 'Rua Raul Ferrari, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '07:00h-17:00h', '07:00h-12:00h', 'PEV', true),
('PEV Campo Grande', 'SP', 'Campinas', 'Jardim Campos Elíseos', 'Avenida Suaçuna, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '07:00h-17:00h', '07:00h-12:00h', 'PEV', true),
('PEV Sousas', 'SP', 'Campinas', 'Sousas', 'Rua Antônio de Castro Figueiredo, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '07:00h-17:00h', '07:00h-12:00h', 'PEV', true),
('Ecoponto - Reciclagem e Sucatas', 'SP', 'Campinas', 'Jardim Chapadão', 'Rua Padre Francisco de Abreu Sampaio, 83', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclagem Campinas', 'SP', 'Campinas', 'Jardim Chapadão', 'Rua Dr. Carlos França, 233', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Trufer Reciclagem', 'SP', 'Campinas', 'Jardim Ipaussurama', 'Avenida John Boyd Dunlop, 2310', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Extra Hipermercados', 'SP', 'Campinas', 'Diversos', 'Diversas unidades', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-22:00h', '08:00h-22:00h', 'Supermercado', true),
('Carrefour', 'SP', 'Campinas', 'Diversos', 'Diversas unidades', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-22:00h', '08:00h-22:00h', 'Supermercado', true),
('Unicamp', 'SP', 'Campinas', 'Cidade Universitária', 'Campus Universitário', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', 'Fechado', 'PEV', true),
('EcoReversa', 'SP', 'Campinas', 'Jardim São Vicente', 'Rua Piracicaba, 1260', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclázaro', 'SP', 'Campinas', 'Centro', 'Rua José Paulino, 3003', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Recilimp', 'SP', 'Campinas', 'Botafogo', 'Rua Sacramento, 1280', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Eco Reciclagem', 'SP', 'Campinas', 'Vila Nova', 'Avenida Andrade Neves, 1589', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Estação Recicla', 'SP', 'Campinas', 'Cambuí', 'Rua Onze de Agosto, 400', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoPonto Betel', 'SP', 'Campinas', 'Betel', 'Rua Betel, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim Satélite Íris', 'SP', 'Campinas', 'Jardim Satélite Íris', 'Rua Dr. Marcelo Mesquita, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Parque Itália', 'SP', 'Campinas', 'Parque Itália', 'Rua Padre Camargo Lacerda, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Dic VI', 'SP', 'Campinas', 'Dic VI', 'Rua Manoel Gomes Ferreira, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim Pacaembu', 'SP', 'Campinas', 'Jardim Pacaembu', 'Rua Prof. Oscar Rodrigues Cajado, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Vila Orozimbo Maia', 'SP', 'Campinas', 'Vila Orozimbo Maia', 'Rua Dr. Aldemar Pereira, 200', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Reciclagem Rio Claro', 'SP', 'Campinas', 'Jardim Chapadão', 'Avenida da Saudade, 2700', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Coopecicla', 'SP', 'Campinas', 'Vila Industrial', 'Rua Carolina Florence, 50', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclar Campinas', 'SP', 'Campinas', 'Botafogo', 'Rua Delfino Cintra, 890', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Eco Reciclagem Nova Campinas', 'SP', 'Campinas', 'Nova Campinas', 'Rua Monte Alegre, 250', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Cooperativa Mãos Dadas', 'SP', 'Campinas', 'Jardim Itatinga', 'Rua Cecília Bueno Bruno, 555', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Swift', 'SP', 'Campinas', 'Swift', 'Rua Abolição, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV São Bernardo', 'SP', 'Campinas', 'São Bernardo', 'Rua Sebastião Gonçalves da Silva, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Vida Nova', 'SP', 'Campinas', 'Vida Nova', 'Rua João Tomazelli, 145', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoRecicla São Quirino', 'SP', 'Campinas', 'São Quirino', 'Rua Dante Suriani, 132', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoCoop Jardim das Paineiras', 'SP', 'Campinas', 'Jardim das Paineiras', 'Avenida Dr. Heitor Penteado, 1640', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Cooperativa de Reciclagem Vida Nova', 'SP', 'Campinas', 'Vida Nova', 'Rua Pedro Zaccarias, 145', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Dic II', 'SP', 'Campinas', 'Dic II', 'Rua Carlos Maia, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim do Lago', 'SP', 'Campinas', 'Jardim do Lago', 'Rua José Rosolém, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Parque das Universidades', 'SP', 'Campinas', 'Parque das Universidades', 'Rua Mirtes Fonseca Santos, 200', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoCoop Jardim Proença', 'SP', 'Campinas', 'Jardim Proença', 'Rua Eduardo Lane, 220', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclar Vila Marieta', 'SP', 'Campinas', 'Vila Marieta', 'Rua Edson Luis Rigonatto, 780', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Santa Genebra', 'SP', 'Campinas', 'Santa Genebra', 'Rua Profa. Therezinha Marcondes Machado, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Jardim Flamboyant', 'SP', 'Campinas', 'Jardim Flamboyant', 'Rua José Teixeira de Camargo, 400', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Reciclar Novo Mundo', 'SP', 'Campinas', 'Novo Mundo', 'Rua Otávio Mendes Alves, 300', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoColeta Campinas', 'SP', 'Campinas', 'Guanabara', 'Rua Barão de Parnaíba, 2340', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclagem A. L.', 'SP', 'Campinas', 'Jardim do Trevo', 'Avenida Prestes Maia, 601', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Cidade Singer', 'SP', 'Campinas', 'Cidade Singer', 'Rua da Abolição, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim Florence', 'SP', 'Campinas', 'Jardim Florence', 'Rua Pedro Vieira dos Santos, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Reciclagem Elite', 'SP', 'Campinas', 'Botafogo', 'Rua Barão de Itapura, 1842', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoPonto Jardim Nova Europa', 'SP', 'Campinas', 'Jardim Nova Europa', 'Rua Piracicaba, 350', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoReciclagem Taquaral', 'SP', 'Campinas', 'Jardim Nossa Senhora Auxiliadora', 'Rua Paschoal Marmo, 2700', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Parque Valença', 'SP', 'Campinas', 'Parque Valença', 'Rua Joaquim Gonçalves Pacheco, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Reciclagem Rápida', 'SP', 'Campinas', 'Centro', 'Rua Marechal Deodoro, 211', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoRecicla Bonfim', 'SP', 'Campinas', 'Bonfim', 'Rua Álvaro Ribeiro, 70', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Cooperativa Ambiental', 'SP', 'Campinas', 'Parque Prado', 'Rua Francisco de Paula Oliveira, 321', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV São José', 'SP', 'Campinas', 'São José', 'Rua Luis Otávio, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim Aurélia', 'SP', 'Campinas', 'Jardim Aurélia', 'Rua José Aparecido Barros Sobrinho, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoReciclagem Bandeiras', 'SP', 'Campinas', 'Jardim das Bandeiras', 'Rua Dr. Álvaro Ribeiro, 10', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Jardim Novo Campos Elíseos', 'SP', 'Campinas', 'Jardim Novo Campos Elíseos', 'Rua Antônio de Souza Noschese, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Cooperativa Caminho Verde', 'SP', 'Campinas', 'Vila Boa Vista', 'Rua Orlando Signorelli, 81', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('EcoRecicla Jardim Guanabara', 'SP', 'Campinas', 'Jardim Guanabara', 'Avenida Barão de Itapura, 2420', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclagem e Sucata Campinas', 'SP', 'Campinas', 'Jardim do Lago II', 'Rua Dona Maria Umbelina Couto, 315', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Jardim Conceição', 'SP', 'Campinas', 'Jardim Conceição', 'Rua Benedito Franco do Amaral, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Jardim Boa Esperança', 'SP', 'Campinas', 'Jardim Boa Esperança', 'Rua Ademar de Barros, 515', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoReciclagem São Martinho', 'SP', 'Campinas', 'São Martinho', 'Rua Maria Emília Alves, 700', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Cooperativa Reciclador Solidário', 'SP', 'Campinas', 'Jardim Paulicéia', 'Rua José Paulino, 5300', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Jardim Santa Mônica', 'SP', 'Campinas', 'Jardim Santa Mônica', 'Rua José Monteiro, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoReciclagem Vila União', 'SP', 'Campinas', 'Vila União', 'Rua Comendador Antônio Alves Aranha, 80', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('Reciclagem Parque Prado', 'SP', 'Campinas', 'Parque Prado', 'Rua Francisco de Paula Oliveira, 321', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Jardim Capivari', 'SP', 'Campinas', 'Jardim Capivari', 'Rua Nelson Fadigati, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Vila Teixeira', 'SP', 'Campinas', 'Vila Teixeira', 'Rua Abolição, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim São Gabriel', 'SP', 'Campinas', 'Jardim São Gabriel', 'Rua Papa Paulo VI, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Vila Marieta', 'SP', 'Campinas', 'Vila Marieta', 'Rua Cel. Quirino, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('PEV Jardim Aurélia II', 'SP', 'Campinas', 'Jardim Aurélia II', 'Rua Edivaldo Antônio Correia, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('EcoPonto Vila Nova', 'SP', 'Campinas', 'Vila Nova', 'Rua Maria Emília Alves, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Cooperativa São Francisco de Assis', 'SP', 'Campinas', 'Jardim Ouro Branco', 'Rua Manoel Afonso Ferreira, 54', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true),
('PEV Jardim Novo Campos Elíseos II', 'SP', 'Campinas', 'Jardim Novo Campos Elíseos II', 'Rua Vitor Meirelles, s/n', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('Reciclagem Parque São Martinho', 'SP', 'Campinas', 'Parque São Martinho', 'Rua José de Oliveira, 305', ARRAY['Coleta seletiva','Óleo de cozinha']::text[], '08:00h-18:00h', '08:00h-12:00h', 'Empresa privada', true);