INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('Hirota - Mooca', 'SP', 'São Paulo', 'Vila Bertioga', 'Rua Teresina, 319', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Super Saudável', 'SP', 'São Paulo', 'Alto de Pinheiros', 'Avenida São Gualter, 931', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('COOP Industrial', 'SP', 'São Paulo', 'Campestre', 'Avenida Industrial, 2001', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Hirota - Campo Belo', 'SP', 'São Paulo', 'Campo Belo', 'Rua Vieira de Morais, 263', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Emporium São Paulo - Jurema', 'SP', 'São Paulo', 'Indianópolis', 'Avenida Jurema, 271', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Hirota - Ipiranga', 'SP', 'São Paulo', 'Ipiranga', 'Avenida Nazaré, 1299', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Emporium São Paulo - Pedroso Alvarenga', 'SP', 'São Paulo', 'Itaim Bibi', 'Rua. R. Pedroso Alvarenga, 803', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Hirota - Saúde', 'SP', 'São Paulo', 'Vila da Saúde', 'Avenida Jabaquara, 1920', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Hirota - Santa Cecília', 'SP', 'São Paulo', 'Santa Cecília', 'Avenida General Olímpio da Silveira, 39', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Hirota - Vila Monumento', 'SP', 'São Paulo', 'Vila Monumento', 'Rua Gaspar Fernandes, 452', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Emporium São Paulo - Afonso Braz', 'SP', 'São Paulo', 'Vila Nova Conceição', 'Rua Afonso Braz, 431', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ecoponto Favela dos Sonhos', 'SP', 'Ferraz de Vasconcelos', 'Jardim São Lázaro', 'R. São Lucas, 4', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('RUA AUGUSTA', 'SP', 'São Paulo', 'Consolação', 'Rua Augusta, 1.600, Consolação, São Paulo – SP CEP', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ARICANDUVA', 'SP', 'São Paulo', 'Jardim Aricanduva', 'Av. Aricanduva, 5555 - Loja Âncora 1', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING BOAVISTA', 'SP', 'São Paulo', 'Santo Amaro', 'Rua Borba Gato, 59 - Lojas L219 e L315', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRAL PLAZA SHOPPING', 'SP', 'São Paulo', 'Vila Prudente', 'Av. Francisco Mesquita N-1000 - Loja Âncora "C" - Vila Prudente
- São Paulo - SP', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CAMPO LIMPO', 'SP', 'São Paulo', 'Vila Prel', 'Estrada do Campo Limpo, 459 - loja âncora A-01', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING IBIRAPUERA', 'SP', 'São Paulo', 'Indianópolis', 'Av. Ibirapuera, 3103 - lojas 4 e 5', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING INTERLAGOS', 'SP', 'São Paulo', 'Campo Grande', 'Av. Interlagos, 2255 - Loja "Arco A"', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING JARDIM SUL', 'SP', 'São Paulo', 'Vila Andrade', 'Avenida Giovanni Gronchi, 5819 - LUC 001', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING MORUMBI', 'SP', 'São Paulo', 'Vila São Francisco', 'Av. Roque Petroni Júnior, 1089 - loja 1', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PENHA', 'SP', 'São Paulo', 'Penha de França', 'Rua Doutor João Ribeiro, 304 Lojas Âncoras C e F', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('RAPOSO SHOPPNG', 'SP', 'São Paulo', 'Jardim Olympia', 'Rodovia Raposo Tavares, s/nº , Km 14,5 - lojas 3001 e 3002', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SANTANA PARQUE SHOPPING', 'SP', 'São Paulo', 'Mandaqui', 'Rua Conselheiro Moreira de Barros, 2780, loja 2011 - 2º
pavimento', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BOURBON SHOPPING POMPÉIA', 'SP', 'São Paulo', 'Perdizes', 'Rua Turiassu, 2.100, loja 117, 2º piso', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CENTER NORTE', 'SP', 'São Paulo', 'Vila Guilherme', 'Travessa Casalbuono, 120 - loja 610', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CANTAREIRA NORTE SHOPPING', 'SP', 'São Paulo', 'Jardim Pirituba', 'Endereço: Avenida Raimundo Pereira de Magalhães, 11.001 –
loja 1002/2002', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ITAQUERA', 'SP', 'São Paulo', 'Itaquera', 'Avenida José Pinheiro Borges, s/nº - lojas 101/201, Gleba I', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING MÓOCA', 'SP', 'São Paulo', 'Vila Prudente', 'Rua Capitão Pacheco e Chaves, 313 – loja 2049', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRO - SÃO PAULO', 'SP', 'São Paulo', 'Centro', 'Rua 24 de Maio, 70', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING D', 'SP', 'São Paulo', 'Canindé', 'Avenida Cruzeiro do Sul, 1.100, SUC 2000, 2º piso', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ELDORADO', 'SP', 'São Paulo', 'Pinheiros', 'Avenida Rebouças, 3970, lojas 231 a 234, 236A, 239, 246 e 279,
1º Piso', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SP MARKET', 'SP', 'São Paulo', 'Vila Almeida', 'Avenida das Nações Unidas, 22.540, loja A7 - 17/18/19, Bloco C', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PLAZA SUL', 'SP', 'São Paulo', 'Jardim da Saúde', 'Pça. Leonor Kaupa, 100 - lojas 119 e 225', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TIETÊ PLAZA', 'SP', 'São Paulo', 'Jardim Íris', 'Avenida Raimundo Pereira de Magalhães, 1465 – loja âncora
1000', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING WEST PLAZA', 'SP', 'São Paulo', 'Água Branca', 'Pça. Tomas Morus, 408 - Bloco B - Térreo - lj.201', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ABC', 'SP', 'Santo André', 'Vila Gilda', 'Av. Pereira Barreto, 42 - Loja Âncora 3', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PRAÇA DA MOÇA', 'SP', 'Diadema', 'Centro', 'Rua Manoel da Nóbrega, 712 - lojas 241 e 301', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MAUÁ PLAZA SHOPPING', 'SP', 'Mauá', 'Jd. Rosina', 'Av. Governador Mário Covas Júnior, 01 - loja 151', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ABC PLAZA', 'SP', 'Jardim Santo André', 'Jardim Santo André', 'Av. Industrial, 600 - Espaço Comercial 223, 224 e 228', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRO - SÃO BERNARDO DO
CAMPO', 'SP', 'S.B. do Campo', 'Centro', 'Rua: Marechal Deodoro, 1078', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METRÓPOLE', 'SP', 'S.B. do Campo', 'Centro', 'Praça Samuel Sabatini, 200, loja LSU-4', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING S.B. PLAZA', 'SP', 'São Bernardo', 'Ferrazópolis', 'Avenida Albert Schweitzer, 256 – loja 1046', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SÃO CAETANO DO SUL', 'SP', 'São Caetano do Sul', 'Cerâmica', 'Alameda Terracota, 545, loja 1007/2007', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRO - SANTO ANDRÉ', 'SP', 'Santo André', 'Centro', 'Rua Campos Salles, 235/247', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BONSUCESSO SHOPPING', 'SP', 'Guarulhos', 'Jardim Albertina', 'Estrada Presidente Juscelino Kubitschek de Oliveira, 5308 - loja
âncora C', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('INTERNACIONAL SHOPPING', 'SP', 'Guarulhos', 'Itapegica', 'Rua Engenheiro Camilo Olivetti, 295 - SUC R01 - R01A2 - M01 -
M02', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRO - GUARULHOS', 'SP', 'Guarulhos', 'Centro', 'Rua Dom Pedro II ,06', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('MOGI SHOPPING', 'SP', 'Mogi das Cruzes', 'Jardim Armênia', 'Avenida Vereador Narciso Yague Guimarães, 1.001, loja A 27', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRO - OSASCO', 'SP', 'Osasco', 'Centro', 'Rua Antônio Agú, 487', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING UNIÃO', 'SP', 'Osasco', 'Vila Yara', 'Avenida dos Autonomistas, 1.400, loja âncora "M"', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PARQUE SHOPPING BARUERI', 'SP', 'Barueri', 'Aldeia', 'Rua General de Divisão de Pedro Rodrigues da Silva, 400 – loja
2037, piso L02', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ITAPECERICA', 'SP', 'Itapecerica da Serra', 'Centro', 'Avenida Quinze de novembro, 89 – loja âncora L2015', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SUZANO', 'SP', 'Suzano', 'Guaio', 'Rua Sete de Setembro, 555, lojas 09/10/11/12/13A/13B', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TAMBORÉ', 'SP', 'Tamboré', 'Tamboré', 'Av. Piracema, 669 - Lojas Âncoras D1 e D2', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BRISAMAR SHOPPING', 'SP', 'São Vincente', 'Centro', 'Rua Frei Gaspar, 365, SUC 312, nível III', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LITORAL SHOPPING', 'SP', 'Praia Grande', 'Intermarés', 'Av. Ayrton Senna da Silva, 1.511 - Loja âncora A6', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PRAIA DO GONZAGA', 'SP', 'Santos', 'Gonzaga', 'Av. Ana Costa, 575/576 e Sobreloja', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ARAÇATUBA SHOPPING', 'SP', 'Araçatuba', 'Jardim Nova Yorque', 'Avenida Joaquim Pompeu de Toledo, 601 - lojas 28 e 29', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING JARAGUÁ', 'SP', 'Araraquara', 'Jardim Bandeirantes', 'Avenida Alberto Benassi, 2.270, loja âncora 27/28/29/30/31, piso térreo', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BAURU SHOPPING', 'SP', 'Bauru', 'Vila Cidade Universitária', 'Rua Henrique Savi, 15-55, loja UN-62', ARRAY['Eletrônicos']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Eldorado', 'SP', 'São Paulo', 'Pinheiros', 'Av. Rebouças, 3970', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Morumbi Shopping', 'SP', 'São Paulo', 'Jardim das Acacias', 'Av. Roque Petroni Júnior, 1089', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Center Norte', 'SP', 'São Paulo', 'Vila Guilherme', 'Tv. Casalbuono, 120', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Ribeirão Shopping', 'SP', 'Ribeirão Preto', 'Res. Florida', 'Av. Cel. Fernando Ferreira Leite, 1540 - 30', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Anália Franco', 'SP', 'São Paulo', 'Vila Reg. Feijó', 'Av. Reg. Feijó, 1739', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Iguatemi Campinas', 'SP', 'Campinas', 'Vila Brandina', 'Av. Iguatemi, 777', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Praiamar Shopping Center', 'SP', 'Santos', 'Aparecida', 'R. Alexandre Martins, 80', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Metrô Tatuapé', 'SP', 'São Paulo', 'Tatuapé', 'R. Domingos Agostim, 91', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Leste Aricanduva', 'SP', 'São Paulo', 'Vila Matilde', 'Avenida Aricanduva, 5555', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Parque Dom Pedro', 'SP', 'Campinas', 'Jardim Santa Genebra', 'Av. Guilherme Campos, 500', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Bourbon Pompéia', 'SP', 'São Paulo', 'Perdizes', 'R. Palestra Itália, 500', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Loja Av. Paulista', 'SP', 'São Paulo', 'Bela Vista', 'Av. Paulista, 1106', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Domingos de Moraes', 'SP', 'São Paulo', 'Vila Mariana', 'R. Domingos de Morais, 2668', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Renner - Shopping Iguatemi JK', 'SP', 'São Paulo', 'Vila Nova Conceição', 'Av. Pres. Juscelino Kubitschek, 2041', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ABC', 'SP', 'Santo André', 'Vila Gilda', 'Avenida Pereira Barreto, 42 - Loja Âncora 3', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PRAÇA NOVA', 'SP', 'Araçatuba', 'Guanabara', 'Avenida CARLOS PEREIRA DA SILVA, 6000 - LUC 106', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('AUGUSTA', 'SP', 'São Paulo', 'Consolação', 'Rua Augusta, 1.600', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ANÁLIA FRANCO', 'SP', 'São Paulo', 'Vila Regente', 'Avenida Reg Feijo Nº 1739 - LOJA OQ 47 48 49 50', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING JARAGUA', 'SP', 'Araraquara', 'Jardim Bandeirantes', 'Avenida Alberto Benassi, 2.270, loja âncora 27/28/29/30/31, piso térreo', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING ARICANDUVA', 'SP', 'São Paulo', 'Jardim Aricanduva', 'Avenida Aricanduva, 5555 - Loja Âncora 1', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BAURU SHOPPING', 'SP', 'Bauru', 'Vila Cidade Universitária', 'Rua Henrique Savi, 15-55, loja UN-62', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING BOA VISTA SP', 'SP', 'São Paulo', 'Santo Amaro', 'Rua Borba Gato, 59 - Lojas L219 e L315', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING BRISAMAR', 'SP', 'São Vincente', 'Centro', 'Rua Frei Gaspar, 365, SUC 312, nível III', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA RUA DE BOTUCATU', 'SP', 'Botucatu', 'Centro', 'RUA AMANDO DE BARROS, 567', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CAMPINAS - CENTRO', 'SP', 'Campinas', 'Centro', 'RUA 13 DE MAIO, 520', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CAMPINAS SHOPPING', 'SP', 'Campinas', 'Jardim do lago', 'RUA JACY TEIXEIRA DE CAMARGO, Nº 940 – ANCORA SCP00603, PISO TÉRREO', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING IGUATEMI CAMPINAS', 'SP', 'Campinas', 'Vila Brandina', 'Avenida IGUATEMI, 777 - LOJA "E"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('CENTRAL PLAZA SHOPPING', 'SP', 'São Paulo', 'Vila Prudente', 'Avenida Francisco Mesquita N-1000 - Loja Âncora "C"', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPP. PARQUE DAS BANDEIRAS', 'SP', 'Campinas', 'Jardim Ipaussurama', 'Avenida John Boyd Dunlop, 3.900, Gleba 60, quarteirão 30020, loja âncora 3001', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PARQUE DOM PEDRO', 'SP', 'Campinas', 'Jardim Santa Genebra', 'Avenida Guilherme Campos, 500 – loja 013', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CAMPO LIMPO', 'SP', 'São Paulo', 'Vila Prel', 'Estrada do Campo Limpo, 459 - loja âncora A-01', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING PRAÇA DA MOÇA', 'SP', 'Diadema', 'Centro', 'Rua Manoel da Nóbrega, 712 - lojas 241 e 301', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('FRANCA SHOPPING', 'SP', 'Franca', 'Estação', 'Avenida Rio Negro, 1.100, loja A-2', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING BONSUCESSO', 'SP', 'Guarulhos', 'Jardim Albertina', 'Estrada Presidente Juscelino Kubitschek de Oliveira, 5308 - loja âncora C', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PARQUE SHOPPING MAIA', 'SP', 'Guarulhos', 'Jardim Flor da Montanha', 'Avenida Bartholomeu de Carlos, 230 – SUC2004', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING INTERNACIONAL', 'SP', 'Guarulhos', 'Itapegica', 'Rua Engenheiro Camilo Olivetti, 295 - SUC R01 - R01A2 - M01 - M02', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('GUARULHOS CENTRO', 'SP', 'Guarulhos', 'Centro', 'Rua Dom Pedro II ,06', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING GRANJA VIANNA', 'SP', 'Cotia', 'Lageadinho', 'Rodovia Raposo Tavares, Km 23,5 – loja 205', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING HORTOLANDIA', 'SP', 'Hortolândia', 'Remanso Campineiro', 'Rua José Camilo de Camargo, 05 – loja âncora 211', ARRAY['Têxtil']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true);