INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('ONG Sem Fronteiras', 'SP', 'Santos', 'Paquetá', 'Rua da Constituição 75', ARRAY['Coleta seletiva']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sociedade Melhoramentos do bairro da Ponta da Praia', 'SP', 'Santos', 'Ponta da Praia', 'Rua Maestro Heitor Vila Lobos, 160', ARRAY['Coleta seletiva']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sociedade de Melhoramentos da Vila Mathias', 'SP', 'Santos', 'Vila Mathias', 'Rua Lucas Fortunato, 45', ARRAY['Coleta seletiva']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sub-prefeitura da Zona Noroeste', 'SP', 'Santos', 'Jd Santa Maria', 'Av. Nossa Senhora de Fátima, 456', ARRAY['Coleta seletiva']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sub-prefeitura dos Morros', 'SP', 'Santos', 'Morro da Nova Cintra', 'Av. Santista, 740', ARRAY['Coleta seletiva']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Emissário de Santos', 'SP', 'Santos', 'JOSÉ MENINO', 'LATERAL DO POSTO 1 PRAIA ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('PRAÇA DA REPÚBLICA', 'SP', 'Santos', 'CENTRO', 'PRAÇA DA REPÚBLICA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('PRAÇA RUI BARBOSA', 'SP', 'Santos', 'CENTRO', 'PRAÇA RUI BARBOSA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('IGREJA - VALONGO', 'SP', 'Santos', 'VALONGO', 'LARGO MARQUES DE MONTE ALEGRE', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM SANTA MARIA', 'JARDIM BOTÂNICO  RUA JOÃO FRACAROLI S/Nº  JARDIM SANTA MARIA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE', 'AV. ALVARO GUIMARÃES Nº 62 ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'VILA SÃO JORGE', 'PRAÇA FRANCISCO PRESTES MAIA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE', 'RUA FRANCISCO DOMENICO ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM SÃO MANOEL', 'PRAÇA NICOLAU GIGAIGIRE  POLICLINICA ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM CANELEIRA', 'RUA ANGELO MARTINS MELEIRO Nº 251 ESQ. COM RUA MIGUEL ROCHA CORREIA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM CASTELO', 'PRAÇA DO 14  (RUA LAURINDO CHAVES/RUA MANOEL FERRAMENTA JUNIOR)', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE', 'VILA CRIATIVA - AV. HUGO MAIA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'NOVA CINTRA', 'PRAÇA GUADALAJARA ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MACUCO', 'RUA 28 DE SETEMBRO Nº 202', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MACUCO', 'RUA BARÃO DE RAMALHO COM RUA JOÃO LUSO Nº 2', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('UME BARÃO DO RIO BRANCO', 'SP', 'Santos', 'CAMPO GRANDE', 'RUA VISCONDE DE CAIRU Nº 217 ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JOSÉ MENINO, EMISSÁRIO DE SANTOS', 'LATERAL DO POSTO 1 PRAIA  Emissário de Santos', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'CENTRO, S/N', 'PRAÇA DA REPÚBLICA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'CENTRO, S/N', 'PRAÇA RUI BARBOSA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'CENTRO, 369', 'AV. SÃO FRANCISCO Nº 369 COM AV. CONSELHEIRO NÉBIAS', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'CENTRO, 541', 'RUA JOÃO PESSOA Nº 541', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'VALONGO, S/N', 'LARGO MARQUES DE MONTE ALEGRE  IGREJA - VALONGO', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM SANTA MARIA, S/N', 'JARDIM BOTÂNICO  RUA JOÃO FRACAROLI S/Nº  JARDIM SANTA MARIA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE, 62', 'AV. ALVARO GUIMARÃES Nº 62  RÁDIO CLUBE', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'VILA SÃO JORGE, S/N', 'PRAÇA FRANCISCO PRESTES MAIA  VILA SÃO JORGE', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM CASATELO, 456', 'AV. AFONSO SCMIDITH Nº 456  CDHU  JARDIM CASATELO', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE, S/N', 'RUA FRANCISCO DOMENICO (INSTALADO PRAÇA DOS EX COMBATENTES)  JD RÁDIO CLUBE', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM SÃO MANOEL, S/N', 'PRAÇA NICOLAU GIGAIGIRE  POLICLINICA  JD. SÃO MANOEL', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM CANELEIRA, 251', 'RUA ANGELO MARTINS MELEIRO Nº 251 ESQ. COM RUA MIGUEL ROCHA CORREIA  JD CANELEIRA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM CASTELO, S/N', 'PRAÇA DO 14  (RUA LAURINDO CHAVES/RUA MANOEL FERRAMENTA JUNIOR)  JARDIM CASTELO', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JARDIM RÁDIO CLUBE, S/N', 'VILA CRIATIVA - AV. HUGO MAIA  JD. RÁDIO CLUBE', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'NOVA CINTRA, S/N', 'PRAÇA GUADALAJARA (IGREJA)  NOVA CINTRA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MACUCO, 202', 'RUA 28 DE SETEMBRO Nº 202  MACUCO (PRÓXIMO À UME PASSOS SOBRINHO)', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MACUCO, 23', 'RUA BARÃO DE RAMALHO COM RUA JOÃO LUSO Nº 23 MACUCO', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'CAMPO GRANDE, 217', 'RUA VISCONDE DE CAIRU Nº 217  UME BARÃO DO RIO BRANCO', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JABAQUARA, S/N', 'LARGO WASHINGTON DI GIOVANNI (FINAL DA AV. RANGEL PESTANA)', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'ENCRUZILHADA, 103', 'RUA CARVALHO DE MENDONÇA Nº 103 ESQUINA COM RUA SENADOR FEIJÓ Nº 664', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'JOSÉ MENINO, S/N', 'PRAÇA WASHINGTON S/N (ORQUIDÁRIO MUNICIPAL)', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MARAPÉ, 240', 'AV. SEN. PINHEIRO MACHADO Nº 240  ESTÁDIO PORTUGUESA SANTISTA', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ponto de coleta de Vidro', 'SP', 'Santos', 'MARAPÉ, S/N', 'AV. NILO PEÇANHA ESQUINA COM RUA NAPOLEÃO LAUREANO  SOCIEDADE MELHORAMENTOS DO MARAPÉ', ARRAY['Coleta seletiva']::text[], 'Não disponível', 'Fechado', 'PEV', true),
('Ecoponto Jardim Armênia', 'SP', 'Mogi das Cinzas', 'Jardim Armênia', 'Rua Júlio Perotti, 353', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-18:00h', '08:00h-18:00h', 'Ecoponto', true),
('Ecoponto Jundiapeba', 'SP', 'Mogi das Cinzas', 'Jundiapeba', 'R. Manoel Fernandes, 44', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-18:00h', '08:00h-18:00h', 'Ecoponto', true),
('Ecoponto Unimed Rio Preto', 'SP', 'São José do Rio Preto', 'Centro', 'R. Penita, 2566 - Centro', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '24h', '24h', 'Ecoponto', true),
('Ponto de Apoio - São Francisco', 'SP', 'São José do Rio Preto', 'São Francisco', 'São José do Rio Preto - SP, 15086', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:30h-18:00h', '08:30h-18:00h', 'Ecoponto', true),
('Shopping Campo Limpo', 'SP', 'São Paulo', 'Campo Limpo', 'Estrada do Campo Limpo, 459', ARRAY['Medicamentos']::text[], '10:00h-22:00h', 'Fechado', 'Drogaria', true),
('Barão de Itapetininga', 'SP', 'São Paulo', 'Centro', 'Rua Barão de Itapetininga, 40', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '08:00h-20:00h', 'Drogaria', true),
('Jardim Bonfiglioli', 'SP', 'São Paulo', 'Jardim Bonfiglioli', 'Praça Isai Leirner, 173', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Doze de Outubro', 'SP', 'São Paulo', 'Lapa', 'Rua Doze de Outubro, 316', ARRAY['Medicamentos']::text[], '07:00h-21:00h', '24h', 'Drogaria', true),
('Angélica', 'SP', 'São Paulo', 'Higienópolis', 'Avenida Angélica, 1397', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('José Paulino', 'SP', 'São Paulo', 'Bom Retiro', 'Rua José Paulino, 577', ARRAY['Medicamentos']::text[], '07:00h-20:00h', '24h', 'Drogaria', true),
('Lapa 2', 'SP', 'São Paulo', 'Lapa', 'Rua Nossa Senhora da Lapa, 171', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '24h', 'Drogaria', true),
('Brigadeiro', 'SP', 'São Paulo', 'Bela Vista', 'Avenida Brigadeiro Luís Antônio, 2064', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '24h', 'Drogaria', true),
('Moóca', 'SP', 'São Paulo', 'Mooca', 'Rua da Mooca, 2526', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '24h', 'Drogaria', true),
('Moema Maracatins', 'SP', 'São Paulo', 'Indianópolis', 'Avenida Juruce, 332', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Augusta', 'SP', 'São Paulo', 'Cerqueira César', 'Rua Augusta, 2899', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '24h', 'Drogaria', true),
('Santo Amaro', 'SP', 'São Paulo', 'Santo Amaro', 'Praça Floriano Peixoto, 18', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '24h', 'Drogaria', true),
('Saúde', 'SP', 'São Paulo', 'Mirandópolis', 'Avenida Jabaquara, 586', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Extra Raposo Tavares', 'SP', 'São Paulo', 'Jardim Pinheiros', 'Avenida Marechal Fiuza de Castro, S/N', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '24h', 'Drogaria', true),
('Tatuapé', 'SP', 'São Paulo', 'Tatuapé', 'Avenida Celso Garcia, 3876', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '24h', 'Drogaria', true),
('Penha', 'SP', 'São Paulo', 'Penha de França', 'Avenida Penha de França, 187', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Tucuruvi', 'SP', 'São Paulo', 'Tucuruvi', 'Avenida Tucuruvi, 403', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Vila Maria', 'SP', 'São Paulo', 'Vila Maria', 'Avenida Guilherme Cotching, 1798', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '24h', 'Drogaria', true),
('Vila Mariana', 'SP', 'São Paulo', 'Vila Mariana', 'Rua Domingos de Morais, 173', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Lapa', 'SP', 'São Paulo', 'Lapa', 'Rua Doze de Outubro, 558', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Teodoro Sampaio', 'SP', 'São Paulo', 'Pinheiros', 'Rua Teodoro Sampaio, 1914', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '24h', 'Drogaria', true),
('Shopping Continental', 'SP', 'São Paulo', 'Vila Lageado', 'Avenida Leão Machado, 100', ARRAY['Medicamentos']::text[], '08:00h-23:00h', '24h', 'Drogaria', true),
('Ipiranga', 'SP', 'São Paulo', 'Ipiranga', 'Rua Silva Bueno, 2130', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Direita', 'SP', 'São Paulo', 'SE', 'Rua Direita, 64', ARRAY['Medicamentos']::text[], '24h', '24h', 'Drogaria', true),
('Brooklin', 'SP', 'São Paulo', 'Brooklin Paulista', 'Rua Joaquim Nabuco, 237', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Shopping Eldorado 1º Piso', 'SP', 'São Paulo', 'Cerqueira César', 'Avenida Rebouças, 3970', ARRAY['Medicamentos']::text[], '10:00h-22:00h', '10:00h-22:00h', 'Drogaria', true),
('Pamplona', 'SP', 'São Paulo', 'Jardim Paulista', 'Rua Pamplona, 1792', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('São Mateus', 'SP', 'São Paulo', 'São Mateus', 'Avenida Mateo Bei, 3329', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-22:00h', 'Drogaria', true),
('Corifeu', 'SP', 'São Paulo', 'Vila Lageado', 'Avenida Corifeu de Azevedo Marques, 3067', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Caetano Álvares', 'SP', 'São Paulo', 'Imirim', 'Avenida Engenheiro Caetano Alvares, 4112', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Shopping Morumbi', 'SP', 'São Paulo', 'Jardim das Acácias', 'Avenida Roque Petroni Junior, 1089', ARRAY['Medicamentos']::text[], '10:00h-22:00h', '10:00h-22:00h', 'Drogaria', true),
('Faria Lima', 'SP', 'São Paulo', 'Jardim Paulistano', 'Avenida Brigadeiro Faria Lima, 2127', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Pompéia Alfonso Bovero', 'SP', 'São Paulo', 'Perdizes', 'Avenida Professor Alfonso Bovero, 1185', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Cambuci', 'SP', 'São Paulo', 'Cambuci', 'Largo Cambuci, 212', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('CR Aricanduva', 'SP', 'São Paulo', 'Jardim Aricanduva', 'Avenida Rio das Pedras, 555', ARRAY['Medicamentos']::text[], '08:00h-23:00h', '08:00h-23:00h', 'Drogaria', true),
('Shopping Jardim Sul', 'SP', 'São Paulo', 'Vila Andrade', 'Avenida Giovanni Gronchi, 5819', ARRAY['Medicamentos']::text[], '09:00h-22:00h', '09:00h-22:00h', 'Drogaria', true),
('Tremembé', 'SP', 'São Paulo', 'Vila Albertina', 'Rua Maria Amalia Lopes Azevedo, 1027', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Avenida Sumaré', 'SP', 'São Paulo', 'Perdizes', 'Avenida Sumaré, 1152', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Real Parque', 'SP', 'São Paulo', 'Morumbi', 'Avenida Morumbi, 6725', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Largo de Pinheiros', 'SP', 'São Paulo', 'Pinheiros', 'Rua Teodoro Sampaio, 2917', ARRAY['Medicamentos']::text[], '07:00h-21:00h', '07:00h-21:00h', 'Drogaria', true),
('CR Anchieta', 'SP', 'São Paulo', 'Ipiranga', 'Avenida Marginal Direita Anchieta, 3398', ARRAY['Medicamentos']::text[], '08:00h-22:00h', '08:00h-22:00h', 'Drogaria', true),
('Extra Morumbi', 'SP', 'São Paulo', 'Jardim Morumbi', 'Avenida Major Sylvio de Magalhães Padilha, 16741', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '07:00h-22:00h', 'Drogaria', true),
('Sete de Abril', 'SP', 'São Paulo', 'República', 'Rua Sete de Abril, 268', ARRAY['Medicamentos']::text[], '07:00h-21:00h', '07:00h-18:00h', 'Drogaria', true),
('Monções', 'SP', 'São Paulo', 'Cid Monções', 'Rua Padre Antônio José dos Santos, 912', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Extra Cidade Dutra', 'SP', 'São Paulo', 'Cidade Dutra', 'Avenida Senador Teotônio Vilela, 2926', ARRAY['Medicamentos']::text[], '07:00h-22:00h', '08:00h-18:00h', 'Drogaria', true),
('CR Raposo', 'SP', 'São Paulo', 'Jardim Cambara', 'Rodovia Raposo Tavares, 0', ARRAY['Medicamentos']::text[], '08:00h-22:00h', '08:00h-22:00h', 'Drogaria', true),
('Pirituba', 'SP', 'São Paulo', 'Vila Pereira Barreto', 'Avenida Benedito Andrade, 80', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Vila Industrial', 'SP', 'São Paulo', 'Jardim Guairaca', 'Avenida do Oratório, 4453', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'Drogaria', true),
('Portal do Morumbi', 'SP', 'São Paulo', 'Jardim Londrina', 'Avenida Dr. Guilherme Dumont Villares, 1078', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Henrique Schaumann', 'SP', 'São Paulo', 'Pinheiros', 'Rua Henrique Schaumann, 630', ARRAY['Medicamentos']::text[], '24h', '07:00h-23:00h', 'Drogaria', true),
('Vila Esperança', 'SP', 'São Paulo', 'Penha de Franca', 'Avenida Amador Bueno da Veiga, 1950', ARRAY['Medicamentos']::text[], '07:00h-23:00h', '07:00h-22:00h', 'Drogaria', true);