INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('Ecoponto Vila Remedi', 'SP', 'Piracicaba', 'Vila Remedi', 'Rua João Laurelli', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '07:00h-18:00h', '07:00h-12:00h', 'Ecoponto', true),
('Ecoponto GERESOL', 'SP', 'Jundiaí', 'Distrito Industrial', 'Av. Yamashita Yukio, 1268  Distrito Industrial', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '07:00h-16:40h', '07:30h-11:30h', 'Ecoponto', true),
('Ecoponto Cidade Nova', 'SP', 'Jundiaí', 'Cidade Nova', 'R. Doraci Camargo Alegre, s/n°  Cidade Nova', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-17:00h', '08:00h-12:00h', 'Ecoponto', true),
('Ecoponto Jardim do Lago', 'SP', 'Jundiaí', 'Jardim do Lago', 'R. Geraldo Santos, 195  Jardim do Lago', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '07:30h-16:00h', '07:00h-15:00h', 'Ecoponto', true),
('Ecoponto Jardim Tarumã', 'SP', 'Jundiaí', 'Jardim Tarumã', 'Rua Rio de Janeiro, s/n  Jardim Tarumã', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-17:00h', '08:00h-12:00h', 'Ecoponto', true),
('Ecoponto Morada das Vinhas', 'SP', 'Jundiaí', 'Parque Cecap', '(Parque Ecológico Morada das Vinhas  José Roberto Mota Barroca) R. Uva Niágara, 376  Parque Cecap', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-17:00h', '08:00h-12:00h', 'Ecoponto', true),
('Ecoponto Residencial Jundiaí', 'SP', 'Jundiaí', 'Parque Residencial Jundiaí', 'Av. Eunice Cavalcante de Souza Queiroz, s/nº  Parque Residencial Jundiaí', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-17:00h', '08:00h-12:00h', 'Ecoponto', true),
('Ecoponto Vila Nambi', 'SP', 'Jundiaí', 'Vila Nambi', 'R. Marquês de Maricá, s/nº  Vila Nambi', ARRAY['Coleta Seletiva','Construção civil','Óleo de cozinha','Eletrônicos','Borracha']::text[], '08:00h-17:00h', '08:00h-12:00h', 'Ecoponto', true),
('Ecoponto Arco-Íris', 'SP', 'Diadema', 'Jardim Arco-Íris', 'Rua Mozart, s/nº  Jardim Arco-Íris', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Arraia', 'SP', 'Diadema', 'Eldorado', 'Rua Arraia, 50  Eldorado', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Marginal Z', 'SP', 'Diadema', 'Parque Real', 'Avenida Daniel José de Carvalho, 330  Parque Real', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Nações', 'SP', 'Diadema', 'Taboão', 'Rua Espanha c/ Avenida Dom João VI  Taboão', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Naval', 'SP', 'Diadema', 'Vila São José', 'Rua Idealópolis c/ Avenida Corredor ABD, s/nº  Vila São José', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Rufino', 'SP', 'Diadema', 'Serraria', 'Estrada do Rufino, 1.059  Serraria', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto Yamagata', 'SP', 'Diadema', 'Jardim Canhema', 'Rua Yamagata c/ Rua Osaka, s/nº  Jardim Canhema', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:30h', '08:00h-13:00h', 'Ecoponto', true),
('Ecoponto João Batista (Vila Nogueira)', 'SP', 'Diadema', 'Vila Nogueira', 'Rua João Batista Alves do Nascimento, 546  Vila Nogueira', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '07:00h-17:00h', '07:00h-16:00h', 'Ecoponto', true),
('Ecoponto DLU', 'SP', 'Diadema', 'Jardim Inamar', 'Avenida Pirâmide, 844  Jardim Inamar', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '07:00h-16:00h', '07:00h-12:00h', 'Ecoponto', true),
('Ecoponto Caracas', 'SP', 'Diadema', 'Vila Mulford', 'Rua Caracas, 120  Vila Mulford (atrás do Corpo de Bombeiros)', ARRAY['Coleta seletiva','Construção civil','Eletrônicos']::text[], '08:00h-16:00h', 'Fechado', 'Ecoponto', true),
('Ecoponto Nova Conquista', 'SP', 'Diadema', 'Vila Nova Conquista', 'Travessa ETCD, 210  Vila Nova Conquista  Piraporinha', ARRAY['Coleta seletiva','Construção civil','Eletrônicos']::text[], '08:00h-16:30h', 'Fechado', 'Ecoponto', true),
('Ecoponto Okavango  Casa Grande', 'SP', 'Diadema', 'Jardim Casa Grande', 'Avenida Casa Grande, 1810  Jardim Casa Grande', ARRAY['Coleta seletiva','Construção civil','Eletrônicos','Borracha']::text[], '08:00h-16:00h', 'Fechado', 'Ecoponto', true),
('Ecoponto Maria Leonor  Parque Reid / Campanário', 'SP', 'Diadema', 'Parque Reid / Campanário', 'Avenida Maria Leonor (sob ponte da Imigrantes)', ARRAY['Coleta seletiva','Construção civil','Eletrônicos']::text[], '08:00h-16:00h', 'Fechado', 'Ecoponto', true),
('Taboão', 'SP', 'Diadema', 'Taboão', 'Av. Prestes Maia, 2080 (em reforma)', ARRAY['Coleta seletiva']::text[], '08:00h-17:00h', '08:00h-17:00h', 'Ecoponto', true),
('Nova Conquista', 'SP', 'Diadema', 'Nova Conquista - Piraporinha', 'Travessa ETCD, 210', ARRAY['Coleta seletiva']::text[], '24h', '24h', 'PEV', true),
('Chico Mendes', 'SP', 'Diadema', 'Jd. União', 'Av. Chico Mendes, 18', ARRAY['Coleta seletiva']::text[], '24h', '24h', 'PEV', true),
('Cooperlimpa', 'SP', 'Diadema', 'Inamar', 'Av. Pirâmide, 144', ARRAY['Coleta seletiva']::text[], '24h', '24h', 'PEV', true),
('MAKRO SANTOS', 'SP', 'Santos', 'Chico de Paula', 'Av. Nossa Senhora de Fátima, 1.440', ARRAY['Obras e materiais']::text[], '07:00h-22:00h', '08:00h-20:00h', 'PEV', true),
('ANDRA', 'SP', 'Santos', 'Vila Matias', 'Av. Senador Feijó, 414', ARRAY['Obras e materiais']::text[], '08:00h-22:00h', '08:00h-20:00h', 'PEV', true),
('ROLDÃO', 'SP', 'Santos', 'Vila Mathias', 'R. Comendador Martins, 241', ARRAY['Obras e materiais']::text[], '08:00h-19:00h', '08:00h-12:00h', 'PEV', true),
('CARREFOUR Praiamar', 'SP', 'Santos', 'Aparecida', 'R. Alexandre Martins, 80 Loja 43', ARRAY['Obras e materiais']::text[], '08:00h-22:00h', '08:00h-20:00h', 'PEV', true),
('CARREFOUR', 'SP', 'Santos', 'Boqueirão', 'R. Conselheiro Nebias, 802', ARRAY['Obras e materiais']::text[], '08:00h-22:00h', '08:00h-20:00h', 'PEV', true),
('VOLTLUZ', 'SP', 'Santos', 'Ponta da Praia', 'Av. Dr. Pedro Lessa, 993', ARRAY['Obras e materiais']::text[], '08:00h-18:00h', '08:00h-12:00h', 'PEV', true),
('CONSTRUDECOR', 'SP', 'Santos', 'Aparecida', 'R. Alexandre Martins, 80', ARRAY['Obras e materiais']::text[], '07:30h-18:00h', '08:00h-12:00h', 'PEV', true),
('ASSAÍ', 'SP', 'Santos', 'Saboo', 'Av. Nossa Senhora de Fátima, 50', ARRAY['Obras e materiais']::text[], '07:00h-22:00h', '07:00h-22:00h', 'PEV', true),
('Pneus Portuária', 'SP', 'Santos', 'Chico de Paula', 'Rua Boris Kaufmam, 261, Chico de Paula', ARRAY['Borracha']::text[], '08:00h-17:00h', 'Fechado', 'PEV', true),
('Atacadão', 'SP', 'Santos', 'Chico de Paula', 'Avenida Nossa Senhora de Fátima, 298 - Chico de Paula', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Carrefour Conselheiro', 'SP', 'Santos', 'Boqueirão', 'Avenida Conselheiro Nébias, 802 - Boqueirão', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Carrefour Praiamar', 'SP', 'Santos', 'Aparecida', 'Rua Alexandre Martins, 80 - Loja 43 - Aparecida', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Empório Nova Era', 'SP', 'Santos', 'Encruzilhada', 'Rua Dr. Cunha Moreira, 210  Encruzilhada', ARRAY['Eletrônicos']::text[], '08:00h-18:00h', 'Fechado', 'PEV', true),
('Fundação Settaport - Centro de Reciclagem de Lixo Eletrônico', 'SP', 'Santos', 'Paquetá', 'Avenida Conselheiro Nébias, 85  Paquetá', ARRAY['Eletrônicos']::text[], '08:30h-18:00h', 'Fechado', 'PEV', true),
('Hipermercado Extra', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 318/340, Gonzaga', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Lojas Cem', 'SP', 'Santos', 'Centro', 'Rua João Pessoa, 185 - Centro', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', 'Fechado', 'PEV', true),
('Makro 82', 'SP', 'Santos', 'Chico de Paula', 'Avenida Nossa Senhora de Fátima, 1440 - Chico de Paula', ARRAY['Eletrônicos']::text[], '07:00h-22:00h', 'Fechado', 'PEV', true),
('Mini Extra 0124', 'SP', 'Santos', 'Ponta da Praia', 'Rua Vereador Henrique Soler, 239 - Ponta da Praia', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Multicoisas - Utilidades Domésticas', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 383  Gonzaga', ARRAY['Eletrônicos']::text[], '09:00h-20:00h', 'Fechado', 'PEV', true),
('Senac Santos', 'SP', 'Santos', 'Vila Mathias', 'Avenida Conselheiro Nébias, 309 - Vila Mathias', ARRAY['Eletrônicos']::text[], '07:30h-23:00h', 'Fechado', 'PEV', true),
('Sindicato do Comércio Varejista da Baixada Santista (SINCOMÉRCIO/BS)', 'SP', 'Santos', 'Vila Mathias', 'Avenida Ana Costa, 25 - Vila Mathias', ARRAY['Eletrônicos']::text[], '08:00h-18:00h', 'Fechado', 'PEV', true),
('Supermercado Bolshoi', 'SP', 'Santos', 'Campo Grande', 'Rua Carvalho de Mendonça, 336 - Campo Grande', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Supermercado Extra', 'SP', 'Santos', 'Boqueirão', 'Avenida Afonso Pena, 270  Boqueirão', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', 'Fechado', 'PEV', true),
('Supermercado Extra', 'SP', 'Santos', 'Centro', 'Avenida Bernardino de Campos, 379', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', '08:00h-22:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Extra)', 'SP', 'Santos', 'Marapé', 'Avenida Senador Pinheiro Machado, 143 - Marapé', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Extra)', 'SP', 'Santos', 'Vila Mathias', 'Avenida Bartolomeu de Gusmão, 45', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Extra) 1747', 'SP', 'Santos', 'Paquetá', 'Avenida Conselheiro Nébias, 867 - Paquetá', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Extra) 1947', 'SP', 'Santos', 'Ponta da Praia', 'Avenida Pedro Lessa, 768 - Ponta da Praia', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Extra)', 'SP', 'Santos', 'Centro', 'Avenida Presidente Wilson, 94/96', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-23:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Mini Extra) 5109', 'SP', 'Santos', 'Centro', 'Rua Amador Bueno, 185 - Centro', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '08:00h-22:00h', 'PEV', true),
('Supermercado Pão de Açúcar (Mini Extra) 5094', 'SP', 'Santos', 'Embaré', 'Rua Oswaldo Cochrane, 220 - Embaré', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '08:00h-22:00h', 'PEV', true),
('Supermercado Varandas', 'SP', 'Santos', 'Vila Mathias', 'Avenida Senador Pinheiro Machado, 643 - Vila Mathias', ARRAY['Eletrônicos']::text[], '07:00h-23:00h', '07:00h-22:00h', 'PEV', true),
('Unimed Santos', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 211/430  Gonzaga', ARRAY['Eletrônicos']::text[], '07:00h-19:00h', 'Fechado', 'PEV', true),
('Casas Bahia', 'SP', 'Santos', 'Gonzaga', 'Avenida Marechal Floriano Peixoto, 22. Gonzaga.', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', '09:00h-19:00h', 'PEV', true),
('Casas Bahia', 'SP', 'Santos', 'Centro', 'Rua Amador Bueno, 28. Centro. CEP: 11013-150.', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', '09:00h-19:00h', 'PEV', true),
('Extra Hyper', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 318/340. Gonzaga. CEP: 11060-000.', ARRAY['Eletrônicos']::text[], '08:00h-22:00h', '08:00h-22:00h', 'PEV', true),
('Kalunga', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 364. Gonzaga', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Makro', 'SP', 'Santos', 'Areia Branca', 'Avenida Nossa Senhora de Fátima, 1440. Areia Branca. ', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Shopping Praiamar', 'SP', 'Santos', 'Aparecida', 'Rua Alexandre Martins, 80. Aparecida. ', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Fundação Settaport - Centro de Reciclagem de Lixo Eletrônico', 'SP', 'Santos', 'Paquetá', 'Av. Conselheiro Nébias, 85 - Paquetá', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Casas Bahia Santos - Gonzaga', 'SP', 'Santos', 'Gonzaga', 'Avenida Marechal Floriano Peixoto, 22. Gonzaga.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Makro Santos - Areia Branca', 'SP', 'Santos', 'Areia Branca', 'Avenida Nossa Senhora de Fátima , 278', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Kalunga  Vila Mathias', 'SP', 'Santos', 'Vila Mathias', 'Avenida Ana Costa, 64', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Shopping Parque Balneário - Gonzaga', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 549.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Shopping Praiamar  Aparecida', 'SP', 'Santos', 'Aparecida', 'Rua Alexandre Martins, 80.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Extra Hiper Santos - Gonzaga', 'SP', 'Santos', 'Gonzaga', 'Avenida Ana Costa, 318/340.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Casas Bahia Santos - Centro', 'SP', 'Santos', 'Centro', 'Rua Amador Bueno, 98.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Carrefour Santos - Boqueirão', 'SP', 'Santos', 'Boqueirão', 'Avenida Conselheiro Nébias, 802.', ARRAY['Eletrônicos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ginásio Rebouças', 'SP', 'Santos', 'Ponta da Praia', 'Praça Engenheiro Rebouças, Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('RC Seguros', 'SP', 'Santos', 'Gonzaga', 'Av. Ana Costa, 452', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Escola Estadual Aristóteles Ferreira', 'SP', 'Santos', 'Aparecida', 'Av. Epitácio Pessoa, 466', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('IBAMA', 'SP', 'Santos', 'Ponta da Praia', 'Av. Cel. Joaquim Montenegro, 297 - Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sociedade de Melhoramento do Bairro Piratininga', 'SP', 'Santos', 'Piratininga', 'Rua Coronel José João Jorge, s/n', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Sociedade de Melhoramento do São Manoel', 'SP', 'Santos', 'São Manoel', 'Praça Nicolau Geraigire, 254', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Associação de Portadores Paralisia Cerebral  A.P.P.C.', 'SP', 'Santos', 'Vila Mathias', 'Av. Senador Pinheiro Machado, 945 ou Av. Afonso Pena, 447', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Avelino da Paz Vieira', 'SP', 'Santos', 'Vila Nova', 'Rua Sete de Setembro, 22 - Vila Nova', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Auxiliadora da Instrução', 'SP', 'Santos', 'Estuário', 'Praça Rubens Ferreira Martins, 8 - Estuário', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Colégio Santista', 'SP', 'Santos', 'Vila Nova', 'Rua Sete de Setembro, 34 - Vila Nova', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Pedro II', 'SP', 'Santos', 'Ponta da Praia', 'Av. Prof. Aristóteles Menezes, 41 - Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Dr. Porchat de Assis', 'SP', 'Santos', 'Ponta da Praia', 'Ana Pimentel 23, Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Avelino da Paz Vieira', 'SP', 'Santos', 'Vila Nova', 'Rua Sete de Setembro, 22 - Vila Nova', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Auxiliadora da Instrução', 'SP', 'Santos', 'Estuário', 'Praça Rubens Ferreira Martins, 8 - Estuário', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Colégio Santista', 'SP', 'Santos', 'Vila Nova', 'Rua Sete de Setembro, 34 - Vila Nova', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Dr. Porchat de Assis', 'SP', 'Santos', 'Ponta da Praia', 'Ana Pimentel 23, Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Gota de Leite', 'SP', 'Santos', 'Encruzilhada', 'R. Xavier Pinheiro, 217 - Encruzilhada', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume João Papa Sobrinho', 'SP', 'Santos', 'Gonzaga', 'R. Goiás, 145 - Gonzaga', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Mario de Almeida Alcântara', 'SP', 'Santos', 'Valongo', 'Rua Mansueto Pierotti, 75 - Valongo', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Dr. Alcides Lobo Viana', 'SP', 'Santos', 'Marapé', 'Av. Sen. Pinheiro Machado, 606  Marapé', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Padre Waldemar Valle Martins', 'SP', 'Santos', 'Macuco', 'R. Vinte e Oito de Setembro, 201 - Macuco', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Ayrton Senna da Silva', 'SP', 'Santos', 'Campo Grande', 'Av. Senador Pinheiro Machado, 617 - Campo Grande', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Maria Luiza Alonso Silva', 'SP', 'Santos', 'Ponta da Praia', 'Próximo a Rua Professor Carlos Escobar, Praça Eng. José Rebouças, S/N - Ponta da Praia', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Leonor Mendes de Barros', 'SP', 'Santos', 'Gonzaga', 'Praça Fernandes Pacheco, 1 - Gonzaga', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Cidade de Santos', 'SP', 'Santos', 'Embaré', 'Av. Sen. Dantas, 410 - Embaré', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Doutor Dino Bueno', 'SP', 'Santos', 'Encruzilhada', 'R. Dr. Cunha Moreira, 134 - Encruzilhada', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true),
('Ume Professor Florestan Fernandes', 'SP', 'Santos', 'Embaré', 'Rua Oswaldo Cochrane, 91 - Embaré', ARRAY['Líquidos']::text[], '09:00h-19:00h', '09:00h-18:00h', 'PEV', true);