INSERT INTO connecteco_ecopontos (name, state, city, neighborhood, full_address, materials, weekday_hours, saturday_hours, company_type, is_active) VALUES
('BOUTIQUE NESPRESSO CENTER NORTE', 'SP', 'São Paulo', 'Vila Guilherme', 'AVENIDA OTTO BAUMGART, 500, TÉRREO (SHOPPING CENTER NORTE), VILA GUILHERME', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('COOPERATIVA COOPERATIVA UNIAO AMBIENTAL E ARTESANAL MOFARREJ', 'SP', 'São Paulo', 'Vila Leopoldina', 'AVENIDA DOUTOR GASTÃO VIDIGAL, 1076 (DEBAIXO DO VIADUTO)', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA PÃO DE AÇÚCAR', 'SP', 'São Paulo', 'Jardim Prudência', 'AV. VEREADOR JOÃO DE LUCA, 1005', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA PÃO DE AÇÚCAR', 'SP', 'São Paulo', 'Campo Belo', 'RUA PEREIRA DA NOBREGA, S/N', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BOUTIQUE NESPRESSO JK IGUATEMI', 'SP', 'São Paulo', 'Vila Nova Conceição', 'AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK, 2041, LOJA 250, PISO XINGU, VILA NOVA CONCEIÇÃO', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('COOPERATIVA COOPERATIVA DE TRABALHADORES DE MATERIAIS RECICLÁVEIS DA FAVELA DE VILA PRUDENTE', 'SP', 'São Paulo', 'Ipiranga', 'RUA CAPITÃO PACHECO E CHAVES , 108', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('BOUTIQUE NESPRESSO ANÁLIA FRANCO', 'SP', 'São Paulo', 'Vila Regente Feijó', 'AVENIDA REGENTE FEIJÓ, 1739, PISO TULIPA; LUC 75 A 77, VILA REGENTE FEIJÓ', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO ADOLFO PINHEIRO', 'SP', 'São Paulo', 'Santo Amaro', 'SP/SÃO PAULO - VILA SUZANA - LOJA PÃO DE AÇÚCAR - R. MARECHAL HASTINFILO DE MOURA, 30,', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO BORBA GATO', 'SP', 'São Paulo', 'Santo Amaro', 'AVENIDA ADOLFO PINHEIRO, 301', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO BUTANTA', 'SP', 'São Paulo', 'Butantã', 'AVENIDA ADOLFO PINHEIROS, 2464', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO CAMPO BELO', 'SP', 'São Paulo', 'Santo Amaro', 'AVENIDA VITAL BRASIL, 333', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO EUCALIPTOS', 'SP', 'São Paulo', 'Moema', 'AVENIDA SANTO AMARO S/N', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO FARIA LIMA', 'SP', 'São Paulo', 'Itaim Bibi', 'AVENIDA IBIRAPUERA, 3144', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO GIOVANI GRONCHI', 'SP', 'São Paulo', 'Santo Amaro', 'AVENIDA BRIGADEIRO FARIA LIMA, 949', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO HOSPITAL SÃO PAULO', 'SP', 'São Paulo', 'Vila Clementino', 'AVENIDA JOÃO DIAS, 5747/ 5745', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO LARGO TREZE', 'SP', 'São Paulo', 'Vila Mascote', 'RUA PEDRO DE TOLEDO, 910', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO LUZ', 'SP', 'São Paulo', 'Santa Ifigênia', 'AVENIDA PADRE JOSÉ MARIA', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO MOEMA', 'SP', 'São Paulo', 'Moema', 'AVENIDA CASPER LIBERO, 598', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO PAULISTA', 'SP', 'São Paulo', 'Cerqueira César', 'AVENIDA IBIRAPUERA', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO PINHEIROS', 'SP', 'São Paulo', 'Vila Mariana', 'RUA DA CONSOLAÇÃO 2367', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO REPUBLICA', 'SP', 'São Paulo', 'Santa Cecília', 'RUA CAPRI, 145', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('ESTACAO SANTA CRUZ', 'SP', 'São Paulo', 'Vila Clementino', 'RUA DO AROUCHE, 24', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('PLAZA SUL SHOPPING', 'SP', 'São Paulo', 'Vila Cruzeiro', 'RUA PEDRO DE TOLEDO, 60', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('POSTO ALICEMAR', 'SP', 'São Paulo', 'São Miguel Paulista', 'PRAÇA LEONOR KAUPA, 100', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('POSTO BARONESA', 'SP', 'São Paulo', 'Higienópolis', 'AVENIDA MARECHAL TITO 6034', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('POSTO DUQUE DUMONT VILLARES', 'SP', 'São Paulo', 'Santana', 'AVENIDA ANGÉLICA, 806', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING SANTANA PARQUE', 'SP', 'São Paulo', 'Lauzane Paulista', 'AVENIDA LUIZ DUMONT VILLARES, 1422', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING CENTER TABOAO', 'SP', 'São Paulo', 'Capão Redondo', 'R. CONSELHEIRO MOREIRA DE BARROS, 2780', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METRO SANTA CRUZ', 'SP', 'São Paulo', 'Vila Mariana', 'ROD. RÉGIS BITTENCOURT, 2643', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING METROPOLE', 'SP', 'São Paulo', 'Centro', 'R. DOMINGOS DE MORAIS, 2564', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('SHOPPING TAMBORE', 'SP', 'São Paulo', 'Tamboré', 'PRAÇA SAMUEL SABATINI, 200', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('VILA PLANA', 'SP', 'São Paulo', 'Jardim São Luís', 'AV. PIRACEMA , 669. TAMBORÉ', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('COOPERATIVA COOPERATIVA DE TRABALHO EM RECICLAGEM UNIDOS VENCEREMOS (UNIVENCE)', 'SP', 'São Paulo', 'Vila Prudente', 'AVENIDA DAS BELEZAS, 880', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('COOPERATIVA COOPERZAGATI', 'SP', 'Suzano', 'Vila Prudente', 'RUA BIOTONICO, 1900', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'Taboão da Serra', 'Jardim São Luís', 'RUA PORFÍRIO HERDEIRO, 440', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Campo Belo', 'AV. VEREADOR JOSÉ DINIZ, 2339', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Moema', 'RUA CANÁRIO, 408, MOEMA', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Morumbi', 'AV. GIOVANNI GRONCHI, 2799', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Perdizes', 'RUA TURIASSÚ, 1205', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Higienópolis', 'AV. ANGÉLICA, 526', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Tatuapé', 'RUA SERRA DE BOTUCATU, 1703', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Vila Nova Conceição', 'RUA ALIANÇA LIBERAL, 322', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('LOJA MAMBO', 'SP', 'São Paulo', 'Pinheiros', 'RUA DEPUTADO LACERDA FRANCO, 553', ARRAY['Cápsulas de café']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Hortolândia', 'Jardim Arpoador', 'Hortolândia, Av.Thereza Ana Cecon Breda, 1896 Vila São Pedro', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Tietê', 'Diadema', 'Tietê, Avenida Onze de Agosto, 130', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Limeira', 'Diadema', 'LIMEIRA, Rua Alfredo Mesanelli 110', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Limeira', 'Macedo', 'LIMEIRA, RUA ANTONIO JORGE LOUREIRO, 303 JD OURO VERDE', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Juquiá', 'Gopoúva', 'Juquiá, Rua Major Martins Coelho, 439 Centro', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Itapetininga', 'Vila Zeferina', 'Itapetininga, R. Dom Joaquim, 495 Centro', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Registro', 'Jardim Gagliardi', 'Registro, AVENIDA DEPUTADO ULISSES GUIMARAES Nosso Teto', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Ponto Faber Castell', 'SP', 'Barra Velha', 'Centro', 'Barra Velha, Rua Marino Atanásio Pinheiro, 51 Jardim Icaraí', ARRAY['Instrumentos de escrita']::text[], 'Não disponível', 'Fechado', 'Empresa privada', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Centro Cívico', 'Rodovia Raposo Tavares KM 14, 153 ao km 18 201 - lado ímpar', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Diadema', 'Vila Jundiaí', 'Rua Manoel da Nóbrega (Prq S Setembro) 712', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Diadema', 'Vila Yara', 'Av. José Bonifácio, 543 543', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Guarulhos', 'Parque Suzano', 'Avenida Paulo Faccini 214', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Guarulhos', 'Nova Petrópolis', 'Rua Guarulhos 2753', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Itaquaquecetuba', 'Alves Dias', 'Avenida Ítalo Adami 1809', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Bernardo do Campo', 'Vila Marlene', 'Rua Passagem da Servidão Toyota 1115', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Mauá', 'Centro', 'Rua Luís Mariani (Vl F N Morelli), 136', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Mogi das Cruzes', 'Santo Amaro', 'Avenida Vereador Narciso Yague Guimarães 1000', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Mogi das Cruzes', 'Cambuci', 'Rua José Galdino de Castro 252', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Osasco', 'Bosque da Saúde', 'Avenida dos Autonomistas 1542', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'Suzano', 'Jardim Aricanduva', 'Avenida Armando Salles de Oliveira 1200', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Bernardo do Campo', 'Vila Gertrudes', 'Avenida Pery Ronchetti 1800', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Bernardo do Campo', 'Rocha', 'Avenida Humberto Alencar Castelo Branco, 3100', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Bernardo do Campo', 'Jardim Cambara', 'Avenida Kennedy 700', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Caetano do Sul', 'Jardim Umuarama', 'Rua Aquidaban S/N', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Campanela', 'Avenida Santo Amaro 4815', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Tatuapé', 'Praça Alberto Lion 100', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Cidade Mãe do Céu', 'Rua Ribeiro Lacerda 940', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Santa Cruz', 'Avenida Rio das Pedras 555', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Guairaca', 'Avenida das Nações Unidas 15187', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Guairaca', 'Rua Juá 264', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Butantã', 'Rodovia Raposo Tavares, 7201 KM 17', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Norma', 'Avenida Interlagos 2501', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Itaim Paulista', 'Avenida José Pinheiro Borges s/n', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Helena', 'Rua Gonçalves Crespo 78', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Tatuapé', 'Rua Domingos Agostim 91', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Cidade Antônio Estevão de Carvalho', 'Rua São Canuto 510', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Beatriz', 'Avenida do Oratório 4500', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Zilda', 'Avenida do Oratório 4500', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Tatuapé', 'Avenida Waldemar Tietz 538', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Canindé', 'Avenida São Miguel 8400', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Bela Vista', 'Avenida Marechal Tito 3333', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Regente Feijó', 'Estrada Itaquera 2000', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Casa Verde', 'Rua Catiguá 255', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Vermelha', 'Rua Boipeva 36', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Brás', 'Rua Doutor Orêncio Vidigal', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Leonor', 'Rua Doutor Ângelo Vita 386', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Mariana', 'Rua Melo Freire s/n', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Mariana', 'Avenida Cruzeiro do Sul s/n', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Socorro', 'Avenida Paulista 2064', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Jaú', 'Avenida Regente Feijó 1759', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Rubi', 'Rua Marambaia 200', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Carlos de Campos', 'Via Anchieta 3398 3398', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Bela Vista', 'Rua Monsenhor Andrade 811', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Penha de França', 'Rua Radiantes 13', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Parque Brasil', 'Avenida Doutor Dante Pazzanese 120', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Jardim Clementino', 'Avenida Doutor Dante Pazzanese 421', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true),
('Exército da Salvação', 'SP', 'São Paulo', 'Vila Mascote', 'Avenida Guarapiranga 752', ARRAY['Têxtil']::text[], '07:00h-22:00h', '09:00h-17:00h', 'PEV', true);