import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="./favicon.ico" />
        <title>ConnectEco</title>
        <meta name="description" content="pagina de ecologia" />
      </head>
      <body className={`pages ${inter.className}`}>
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
